### PR TITLE
file splitting

### PR DESCRIPTION
**Pull request by lamyro**
Feel free to comment and suggest changes for the files structure of botto

### CODE REVIEW

**Comment by LaiAlexander** [comment]
Hello!
Does this run on your machine? Can't get it to run on my machine, stopped by "Failed RTM connect"
```
$ python esnbot/esnbot.py
Failed RTM connect
Traceback (most recent call last):
  File "D:\Lai Alexander\Programming\Python\ESNbot\env\lib\site-packages\slackclient\client.py", line 140, in rtm_connect
    self.server.rtm_connect(use_rtm_start=with_team_state, **kwargs)
  File "D:\Lai Alexander\Programming\Python\ESNbot\env\lib\site-packages\slackclient\server.py", line 163, in rtm_connect
    raise SlackLoginError(reply=reply)
slackclient.server.SlackLoginError
secret-dev.env loaded...
18-10-2023 14:47:32: Connection failed.
(env)
```

Apart from that I think this looks sensible, but may I suggest that we follow the structure outlined [here](https://docs.python-guide.org/writing/structure/) instead? Look at [pycord](https://github.com/Pycord-Development/pycord) for an example of this structure.
I.e. something like this:
```
.
├── README.md
├── noxfile.py
├── pyproject.toml
├── setup.py
├── awesome_package/
│   ├── __init__.py
│   └── module.py
└── tools/
    ├── generate_awesomeness.py
    └── decrease_world_suck.py
```
It's not a huge difference, but I think that this structure is more commonly used. 

May also nicely reuse modules like this as well, as per [this SO post](https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application):
> I recommend putting all of this under the "name-of-my-product" directory. So, if you're writing an application named quux, the directory that contains all this stuff is named /quux.
> 
> Another project's PYTHONPATH, then, can include /path/to/quux/foo to reuse the QUUX.foo module.

**Comment by LaiAlexander** [comment]
Wall of text incoming, sorry in advance.

The error mentioned earlier happens because slack_client is instantiated before SLACK_BOT_TOKEN exists.
image
Marked in red is the instantiation, in orange is the loading of the environment variables. 

`slack_client = SlackClient(os.environ.get("SLACK_BOT_TOKEN")) #pylint: disable=invalid-name`
This line might be better suited to be a part of the esnbot.py, not slackutils.py. It is not a utility line, it is the core of actually creating the slack client. If that is to be moved, some of the functions has to be changed as well, slack_client needs to be passed on as a parameter. E.g. this line will not work is the aforementioned line is moved from slackutils to esnbot.py:
`slack_client.api_call("chat.postMessage", channel=channel, as_user=True, text=message)`

In the present state most commands/functions break as well.
Some examples:
```
19-10-2023 16:43:28: Command used was 'list'
Traceback (most recent call last):
  File "src/esnbot.py", line 107, in <module>
    run()
  File "src/esnbot.py", line 101, in run
    handle_command(text, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 92, in handle_command
    choose_command(command, arguments, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 104, in choose_command
    func = constants.cmds[command]
AttributeError: module 'constants' has no attribute 'cmds'
```
This stems from slackutils.choose_command(). `func = constants.cmds[command]`

image
```
19-10-2023 17:40:45: Command used was 'nonexisting-command'
Traceback (most recent call last):
  File "src/esnbot.py", line 107, in <module>
    run()
  File "src/esnbot.py", line 101, in run
    handle_command(text, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 92, in handle_command
    choose_command(command, arguments, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 104, in choose_command
    func = constants.cmds[command]
AttributeError: module 'constants' has no attribute 'cmds'
```
This shouldn't first respond that the bot doesn't understand the command, and then try to execute the command anyway. The logic has been changed here. Here the exception comes from the same spot as earlier, however if we fix this, the exception will come from constants.COMMANDS, because the key is non-exisitent in that dictionary.

```
19-10-2023 17:51:29: Command used was 'help'
Traceback (most recent call last):
  File "src/esnbot.py", line 96, in <module>
    run()
  File "src/esnbot.py", line 90, in run
    handle_command(text, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 92, in handle_command
    choose_command(command, arguments, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 106, in choose_command
    return func(channel, user, arguments, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\commands\help.py", line 7, in command
    if argument[0].lower() in constants.COMMAND_HELP:
AttributeError: module 'constants' has no attribute 'COMMAND_HELP'
```
From help.command:
```
    if argument[0].lower() in constants.COMMAND_HELP:
        slack.respond_to(channel, user, "`" + argument[0].lower() + "`\n" + constants.COMMAND_HELP[argument[0]])

```

```
19-10-2023 18:00:28: Command used was 'coverphoto'
19-10-2023 18:00:28: Arguments supplied by user: []
Traceback (most recent call last):
  File "src/esnbot.py", line 96, in <module>
    run()
  File "src/esnbot.py", line 90, in run
    handle_command(text, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 92, in handle_command
    choose_command(command, arguments, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 106, in choose_command
    return func(channel, user, arguments, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\commands\coverphoto.py", line 12, in command
    commands.help(channel, ["coverphoto"], user, output)
TypeError: 'module' object is not callable
```

This is coverphoto called without an image attached, which means it should respond with the help text for coverphoto instead of trying to create an image.

```
19-10-2023 18:01:45: Command used was 'watermark'
19-10-2023 18:01:45: Arguments supplied by user: []
Traceback (most recent call last):
  File "src/esnbot.py", line 96, in <module>
    run()
  File "src/esnbot.py", line 90, in run
    handle_command(text, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 92, in handle_command
    choose_command(command, arguments, channel, user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\slackutils.py", line 106, in choose_command
    return func(channel, user, arguments, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\commands\watermark.py", line 73, in command
    commands.help.command(channel, ["watermark"], user, output)
  File "D:\Lai Alexander\Programming\Python\ESNbot\src\commands\help.py", line 7, in command
    if argument[0].lower() in constants.COMMAND_HELP:
AttributeError: module 'constants' has no attribute 'COMMAND_HELP'
```
The same kind of error happens in watermark if it's called without an image attached.


The other commands seem to work allright. Coverphoto and watermark works if an image (and arguments) is supplied.


I have one additional question/request regarding the restructuring. I feel that coverphoto.py and watermark.py should remain as they were. As they are in the master branch, they both handle the image creation/manipulation as standalone modules. This way the can easily be used by other parts of the bot as well. Watermark could be used in other commands, and then it makes no sense to have to import commands.watermark.foo, when you aren't interested in the commands at all, only the image functionality. The same goes for coverphoto. As I understand it's on the horizon to expand the functionality to create coverphotos for activites.esn.org (and maybe hoopla) as well. If they end up being separate commands, then again it doesn't make sense to have to import a command to use the image creation functionalities of said commands.

Also when/if we have a test suite, we should test the image creation. Then it makes more sense to test the module watermark.py or coverphoto.py to verify that the image creation works properly. It's not intuitive to have to test commands.watermark if it's the watermark functionality that is to be tested.

For these to it makes way more sense to leave the files as is, then have the commands.coverphoto and commands.watermark only actually contain the command part of the functions. 

This is also how the gsheets.py module is split as of now, and that makes way more sense to me.

A last thought:
Is it best to have the different commands like this:
```
.
├── commands/
│   ├── __init__.py
│   ├── foo.py
│   ├── bar.py
│   └── baz.py
```
Or is it better to collect the different commands simply in a file/module called `commands.py`?
I'm not sure.

I can probably make PR for this branch with some of these changes/fixes some time tomorrow if that would be useful.

**Comment by hansmariusoveras** [comment]
I have updated the code with your suggestions (in addition to some of my own ideas). I ended up making the bot code into a class, because then it can pass itself with all the functions it uses down to the command functions, which in my opinion reduces the complexity of having to import so much stuff.

I also tried to make sure that each file only contains relevant code. I ended up deleting slackutils, because I think most of that code should rather live in esnbot. Particularly, I wanted `SlackClient` to never be referenced from another file. There are probably a million ways to do this, so I'm sure the way I did it now is not the best.

I think most of the bugs you refer to are caused by me trying to convert if/else-statements to early return statements instead, and failing at adding the return. Should be fixed now, I've verfified that all the commands run (I hope).

**Review by LaiAlexander — APPROVED** [review]
Looks good. Files and functionality are splitting in a sensible way, and functionality seems to be preserved from what I can tell. I've tested some of the commands (not all of them) and they behave correctly.

**Pull request merged**
